### ISSUE TITLE
Allow for reading/writing stdin/stdout by default

### ISSUE THREAD

**Issue by niemasd** [ERSP-HIV-Phylogenetics-and-Transmission/erspMeasure#4]
It may be useful to have a user specify an input ordering file via `-i`, and have it default to `stdin` if they don't specify a file, and then also have a user specify an output file via `-o`, and have it default to `stdout` if they don't specify a file

See TreeCluster for an example:

https://github.com/niemasd/TreeCluster/blob/master/TreeCluster.py#L570

**Comment by Titan-Ngo** [comment]
Write a main in orderCheck to handle this
